# Generated by Django 4.2 on 2023-04-25 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('active', 'Активная'), ('ordered', 'Оформленная'), ('cancelled', 'Отмененная'), ('refunded', 'Возврат'), ('completed', 'Завершенная')], default='new', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Подарок',
                'verbose_name_plural': 'Подарки',
            },
        ),
        migrations.CreateModel(
            name='GiftCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('code', models.CharField(max_length=64, verbose_name='Купон')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_data', models.DateField(verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.gift', verbose_name='Подарок')),
            ],
            options={
                'verbose_name': 'Купон подарка',
                'verbose_name_plural': 'Купоны подарков',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('discount_type', models.CharField(choices=[('percent', 'Процентная'), ('fixed', 'Фиксированная')], verbose_name='Тип скидки')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Значение скидки')),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Минимальная сумма для работы скидки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('categories', models.ManyToManyField(blank=True, null=True, to='shop.categorynode')),
                ('products', models.ManyToManyField(blank=True, null=True, to='shop.producttype')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('code', models.CharField(max_length=64, verbose_name='Купон')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_data', models.DateField(verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.discount', verbose_name='Скидка для купона')),
            ],
            options={
                'verbose_name': 'Купон',
                'verbose_name_plural': 'Купоны',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart', verbose_name='Корзина')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в корзине',
                'verbose_name_plural': 'Товары в корзине',
            },
        ),
    ]
