# Generated by Django 4.2 on 2023-04-27 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_options_alter_producttype_options_and_more'),
        ('cart', '0005_order_orderdetail'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
