# Generated by Django 4.2 on 2023-05-04 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_favorite_client_alter_favorite_product_and_more'),
        ('shop', '0006_alter_categorynode_category_and_more'),
        ('cart', '0008_alter_cart_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carts', to='user.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='cart.cart', verbose_name='Корзина'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cart.discount', verbose_name='Скидка для купона'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='categories',
            field=models.ManyToManyField(to='shop.categorynode'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='products',
            field=models.ManyToManyField(to='shop.producttype'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='giftcoupon',
            name='gift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cart.gift', verbose_name='Подарок'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cart.cart', verbose_name='Корзина'),
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cart.coupon', verbose_name='Купон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cart.discount', verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='gift_coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cart.giftcoupon', verbose_name='Купон подарка'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cart.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product', verbose_name='Товар'),
        ),
    ]
