# Generated by Django 4.2 on 2023-04-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageledger', '0001_initial'),
        ('shop', '0002_producttype_poster_alter_categorynode_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='description',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='slug',
            field=models.SlugField(max_length=110, verbose_name='Транслит'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='description',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='slug',
            field=models.SlugField(verbose_name='Транслит'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='meaning',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='product_images', to='imageledger.imageledger', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
    ]
