# Generated by Django 4.2 on 2023-04-27 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
        ('shop', '0004_alter_product_options_alter_producttype_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('product', 'warehouse')},
        ),
    ]
