# Generated by Django 4.2 on 2023-05-04 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_alter_warehouse_city'),
        ('shop', '0005_alter_product_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorynode',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_nodes', to='shop.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='categorynode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='childrens', to='shop.categorynode', verbose_name='ID подкатегории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.producttype', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='guide.warehouse', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.attribute', verbose_name='Аттрибуты'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributes', to='shop.producttype', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.attributevalue', verbose_name='Величина'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_types', to='guide.brand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_types', to='shop.categorynode', verbose_name='Категория'),
        ),
    ]
