# Generated by Django 4.2 on 2023-04-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='categorynode',
            options={'verbose_name': 'подкатегоря', 'verbose_name_plural': 'подкатегории'},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=120, null=True, verbose_name='описание'),
        ),
    ]
