# Generated by Django 4.2 on 2023-04-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_options_alter_categorynode_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id категории'),
        ),
        migrations.AlterField(
            model_name='categorynode',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id подкатегории'),
        ),
        migrations.AlterField(
            model_name='categorynode',
            name='parent_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='родитель'),
        ),
    ]
