# Generated by Django 4.2 on 2023-04-15 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_category_description_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorynode',
            name='parent_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.categorynode', verbose_name='категория'),
            preserve_default=False,
        ),
    ]
