# Generated by Django 4.2 on 2023-04-15 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_categorynode_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorynode',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.categorynode', verbose_name='категория'),
        ),
    ]
