# Generated by Django 4.2 on 2023-04-15 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_categorynode_parent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorynode',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
