# Generated by Django 4.2 on 2023-04-16 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('product', '0006_rename_parent_id_categorynode_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('article', models.IntegerField(primary_key=True, serialize=False, verbose_name='артикул товара')),
                ('name', models.CharField(max_length=60, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='базовая цена')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена со скидкой')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_types', to='product.categorynode', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'тип товара',
                'verbose_name_plural': 'типы товаров',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('quantity', models.IntegerField(default=0, verbose_name='количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.producttype', verbose_name='тип товара')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.shop', verbose_name='магазин')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
    ]
