# Generated by Django 4.2 on 2023-04-17 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_city_options_alter_shop_options_and_more'),
        ('product', '0009_alter_category_options_alter_categorynode_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name': 'Тип товара', 'verbose_name_plural': 'Типы товаров'},
        ),
        migrations.AlterField(
            model_name='product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.producttype', verbose_name='Тип товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.shop', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='article',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Артикул товара'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базовая цена'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_types', to='product.categorynode', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена со скидкой'),
        ),
    ]
