# Generated by Django 4.2 on 2023-04-17 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('product', '0010_alter_product_options_alter_producttype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_types', to='brands.brand', verbose_name='Бренд'),
        ),
    ]
