# Generated by Django 4.2 on 2023-04-17 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_attribute_productattribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=64, null=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Значение атрибута',
                'verbose_name_plural': 'Значение атрибутов',
            },
        ),
        migrations.AddField(
            model_name='attribute',
            name='description',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='meaning',
            field=models.CharField(default=1, max_length=64, verbose_name='Значение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.attributevalue', verbose_name='Величина'),
        ),
    ]
