# Generated by Django 4.2 on 2023-04-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageledger', '0001_initial'),
        ('product', '0015_producttype_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='imageledger.imageledger'),
        ),
    ]
