# Generated by Django 4.2 on 2023-04-25 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='phone',
        ),
        migrations.AddField(
            model_name='review',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.client', verbose_name='Клиент'),
            preserve_default=False,
        ),
    ]
