# Generated by Django 4.2 on 2023-05-04 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_categorynode_category_and_more'),
        ('user', '0003_remove_review_name_remove_review_phone_review_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.client', verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.producttype', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='review',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='shop.producttype', verbose_name='Товар'),
        ),
    ]
